### ISSUE TITLE
LSDJ Support

### ISSUE THREAD

**Issue by peterswimm** [timheigames/Peanut-GB-Playdate#2]
Would be great to support this music app!

https://www.littlesounddj.com/lsd/latest/rom_images/

**Comment by timheigames** [comment]
Unfortunately I am not familiar enough with Gameboy emulation to know how to solve compatibility issues. This would be something that would need to be fixed with the underlying [Peanut-GB](https://github.com/deltabeard/Peanut-GB) code, which I did not write myself.
