### ISSUE TITLE
Fails to Load in Simulator

### ISSUE THREAD

**Issue by mhughson** [timheigames/Peanut-GB-Playdate#3]
I am unable to load the emulator in the playdate simulator. I had the same issue with GameKid, so maybe I am doing something wrong?

```
11:06:16: Loading: C:\Users\Matt\Downloads\peanutGB_Playdate.pdx\peanutGB_Playdate.pdx
11:06:16: Loading: Failed
Load failed: /
```
![image](https://user-images.githubusercontent.com/310185/167917152-632f186c-40f2-43ca-9ce0-38318a50fed7.png)

**Comment by timheigames** [comment]
I didn't include the Windows Simulator binary in the release section since I didn't expect people to try and run in the Simulator. Gamekid only includes the Mac Simulator binary so it won't work on Windows. Is there a reason you want to run in the Simulator?

**Comment by mhughson** [comment]
I don't own a playdate, and I wanted to see how my game runs in the emulator (I make modern GB homebrew).

**Comment by timheigames** [comment]
I added a Windows Simulator build to the Releases section, so you should be able to run it now!
